import Head from "next/head"
import { useFormik } from "formik"
import { HcardBuilderForm } from "@/pages/HcardBuilderForm"
import { Grid } from "@mui/material"
import { HcardPreviewCard } from "@/pages/HcardPreviewCard"
import { HcardBuilderFormData } from "@/pages/hcardBuilderFormData"

export default function Home() {
	const formikProps = useFormik<HcardBuilderFormData>({
		initialValues: {
			givenName: null,
			surname: null,
			email: null,
			phone: null,
			streetNumber: null,
			streetName: null,
			suburn: null,
			state: null,
			postCode: null,
			country: null,
			imageUrl: null
		},
		onSubmit(values) {
			// TODO: Once a backend is setup for this,
			// the submission of the form will be completed.
		}
	})

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Grid container height="100vh">
					<Grid item xs={12} md={6} mb={{ xs: 2 }}>
						<HcardBuilderForm formikProps={formikProps} />
					</Grid>
					<Grid sx={{ backgroundColor: "#E6E7EB" }} item xs={12} md={6}>
						<HcardPreviewCard formikProps={formikProps} />
					</Grid>
				</Grid>
			</main>
		</>
	)
}
